use_frameworks!

target 'ViewStyles_Example' do
  pod 'ViewStyles', :path => '../'
  pod 'SnapKit'
  target 'ViewStyles_Tests' do
    inherit! :search_paths
    pod 'FBSnapshotTestCase'
    
  end
end
